sudo: enabled
osx_image: xcode9.2
language: objective-c
xcode_project: MVVM.xcodeproj # path to your xcodeproj folder
xcode_scheme: MVVM

before_install:
- rm -rf ~/Library/Developer/Xcode/DerivedData

before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
- sudo gem install cocoapods --pre
- pod repo update
- pod install

script:
- xcodebuild -version
- xcodebuild -workspace MVVM.xcworkspace -scheme 'MVVM' -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s" clean build